print('===Cadastro da Escola===')
nome = input('Digite o nome: ')
print('Bem vindo(a) '+nome)
lazer = input('O que gosta de fazer?')
print(lazer)
cor = input('Qual sua cor preferida?')
print = (cor)
time = input('Qual o seu time de futebol?')
print('Time do coração '+time)